// English (football-data.org) -> Spanish country names.
// Keyed lowercased; includes common API aliases. Unknown -> returned as-is.

const ES: Record<string, string> = {
  // CONMEBOL
  argentina: 'Argentina',
  brazil: 'Brasil',
  uruguay: 'Uruguay',
  colombia: 'Colombia',
  ecuador: 'Ecuador',
  peru: 'Perú',
  paraguay: 'Paraguay',
  chile: 'Chile',
  bolivia: 'Bolivia',
  venezuela: 'Venezuela',

  // UEFA
  france: 'Francia',
  spain: 'España',
  germany: 'Alemania',
  england: 'Inglaterra',
  portugal: 'Portugal',
  netherlands: 'Países Bajos',
  holland: 'Países Bajos',
  belgium: 'Bélgica',
  italy: 'Italia',
  croatia: 'Croacia',
  switzerland: 'Suiza',
  denmark: 'Dinamarca',
  sweden: 'Suecia',
  norway: 'Noruega',
  poland: 'Polonia',
  serbia: 'Serbia',
  austria: 'Austria',
  wales: 'Gales',
  scotland: 'Escocia',
  'republic of ireland': 'Irlanda',
  ireland: 'Irlanda',
  'northern ireland': 'Irlanda del Norte',
  turkey: 'Turquía',
  'türkiye': 'Turquía',
  turkiye: 'Turquía',
  greece: 'Grecia',
  ukraine: 'Ucrania',
  'czech republic': 'República Checa',
  czechia: 'República Checa',
  hungary: 'Hungría',
  romania: 'Rumania',
  slovenia: 'Eslovenia',
  slovakia: 'Eslovaquia',
  'bosnia and herzegovina': 'Bosnia y Herzegovina',
  'north macedonia': 'Macedonia del Norte',
  albania: 'Albania',
  iceland: 'Islandia',
  finland: 'Finlandia',
  russia: 'Rusia',
  georgia: 'Georgia',

  // CONCACAF
  'united states': 'Estados Unidos',
  usa: 'Estados Unidos',
  mexico: 'México',
  canada: 'Canadá',
  'costa rica': 'Costa Rica',
  panama: 'Panamá',
  jamaica: 'Jamaica',
  honduras: 'Honduras',
  'el salvador': 'El Salvador',
  guatemala: 'Guatemala',
  'trinidad and tobago': 'Trinidad y Tobago',
  haiti: 'Haití',
  'curacao': 'Curazao',
  'curaçao': 'Curazao',

  // CAF
  morocco: 'Marruecos',
  senegal: 'Senegal',
  tunisia: 'Túnez',
  algeria: 'Argelia',
  egypt: 'Egipto',
  nigeria: 'Nigeria',
  ghana: 'Ghana',
  cameroon: 'Camerún',
  'ivory coast': 'Costa de Marfil',
  "cote d'ivoire": 'Costa de Marfil',
  "côte d'ivoire": 'Costa de Marfil',
  mali: 'Malí',
  'burkina faso': 'Burkina Faso',
  'south africa': 'Sudáfrica',
  'cape verde': 'Cabo Verde',
  'cabo verde': 'Cabo Verde',
  'dr congo': 'RD Congo',
  'congo dr': 'RD Congo',
  'democratic republic of the congo': 'RD Congo',
  gabon: 'Gabón',
  guinea: 'Guinea',
  'equatorial guinea': 'Guinea Ecuatorial',
  angola: 'Angola',
  zambia: 'Zambia',
  'south sudan': 'Sudán del Sur',
  benin: 'Benín',

  // AFC
  japan: 'Japón',
  'south korea': 'Corea del Sur',
  'korea republic': 'Corea del Sur',
  'iran': 'Irán',
  'ir iran': 'Irán',
  'saudi arabia': 'Arabia Saudita',
  australia: 'Australia',
  qatar: 'Catar',
  iraq: 'Irak',
  'united arab emirates': 'Emiratos Árabes Unidos',
  uzbekistan: 'Uzbekistán',
  jordan: 'Jordania',
  oman: 'Omán',
  bahrain: 'Baréin',
  china: 'China',
  'china pr': 'China',
  'north korea': 'Corea del Norte',
  'korea dpr': 'Corea del Norte',
  indonesia: 'Indonesia',
  thailand: 'Tailandia',
  vietnam: 'Vietnam',
  india: 'India',
  palestine: 'Palestina',

  // OFC
  'new zealand': 'Nueva Zelanda',
};

export function teamName(name: string | null | undefined): string {
  if (!name) return '';
  return ES[name.trim().toLowerCase()] ?? name;
}
